### ISSUE TITLE
Dev Conference

### ISSUE THREAD

**Issue by JuanPabloDiaz** [marcelscruz/dev-resources#448]
I was wondering if it would be a good idea to add a dedicated category or sub-category called Tech/dev Conferences🤔

What do you think?

**Comment by marcelscruz** [comment]
I think that's a great idea @JuanPabloDiaz!
Do you have a list of some that we could get started with?
Happy to assist you with adding the new category, if you need help.

**Comment by JuanPabloDiaz** [comment]
@marcelscruz, 
How can I run the project and view the project in the browser on localhost?

**Comment by JuanPabloDiaz** [comment]
How can I create the category? just add it to the `categories.json` file? Do I need to do anything in the `resources.json` as well?

**Comment by JuanPabloDiaz** [comment]
Was this the project in it's early days? https://dev-resources.vercel.app/

**Comment by marcelscruz** [comment]
> @marcelscruz, How can I run the project and view the project in the browser on localhost?

If you're asking about the website, that part is not open-source.
For this repository though you can run the scripts listed on `package.json` locally to see the changes in place, but there's actually no need to do it before opening a PR, because the scripts will be automatically run on every merge.

> How can I create the category? just add it to the `categories.json` file? Do I need to do anything in the `resources.json` as well?

To add a new category go to `/types/category.ts` and add it there.
The files inside `/db` are auto-generated, so please don't modify them.

> Was this the project in it's early days? https://dev-resources.vercel.app/
> I was looking at previous commits to see I could figure out what do I need to do to create the new category

Not really, this isn't mine, but nice catch!

**Comment by JuanPabloDiaz** [comment]
>If you're asking about the website, that part is not open-source.

Thank you for the clarification. I was hoping to explore the website further, but I understand that it’s not open-source. I appreciate your response!

> To add a new category go to /types/category.ts and add it there.

Then, it should be good.

**Comment by marcelscruz** [comment]
[Merged](https://github.com/marcelscruz/dev-resources/pull/463)!
